### ISSUE TITLE
Repo starts but starting openrefine creates internal server error

### ISSUE THREAD

**Issue by ssp24** [innovationOUtside/nb_serverproxy_openrefine#11]
Hi, and first of all thanks very much for the work and instructions. After having had a lot of issues recently with betatims version I found this repo. I have been successful in starting binder with it, but when I click on the tile to start open refinde I get an internal server error. This also happens when I try to access open refine directly via the link provided. Is there any chance this could be fixed? 

Thanks in advance!

**Comment by psychemedia** [comment]
The binder part of this repo is rather old.. I will trynto have a look at it this week.

**Comment by ssp24** [comment]
That would be fantastic, thanks!

**Comment by psychemedia** [comment]
I updated the java package and the openrefine package, but Binder just sits for me on the `Pulling image` step (minutes and minutes...). Please let me know if you can actually get an image to launch, and if so, whether it works.

**Comment by psychemedia** [comment]
Okay - seems to run okay now either from Binder open to openrefine link, or via launcher icon in Jupyterlab

**Comment by ssp24** [comment]
Thank you very much! That is awesome!
