### ISSUE TITLE
 500 : Internal Server Error on newer nbclassic

### ISSUE THREAD

**Issue by vivian-rook** [innovationOUtside/nb_serverproxy_openrefine#6]
When running nbclassic 0.4.3 I'm getting a 500 : Internal Server Error through jupyterhub when opening openrefine. This works with nbclassic 0.3.7

Few details at https://phabricator.wikimedia.org/T312251

**Comment by psychemedia** [comment]
I recently updated the package but didn't test the updates... do you get the same error with the previous version,  `pip install nb-serverproxy-openrefine==0.0.4` ?

**Comment by vivian-rook** [comment]
Sorry I didn't write this ticket correctly. I'm not having luck getting this working with nbclassic 0.3.7 as well. Suggesting to me that it is that some weirdness that we are engaging in for PAWS is likely to be the issue, though haven't identified what it might be yet.

For what it's worth I did try with 0.0.4 and getting jupyterlab and jupyterhub upgraded, though always got a 500. nb_serverproxy_openrefine does get me closer, as I do have a openrefine tile when I run it, unlike the PAWS method that we're running, tile vanishes when updating nbclassic.
